version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - management-service

  management-service:
    image: orbsnetworkstaging/management-service:v2.5.1-a4db0333
    command: [ "npm", "start", "--", "--config", "/opt/orbs/config.json" ]
    volumes:
        # TEMP: should take values from node.env
      - ./config.json:/opt/orbs/config.json
      # This is done to expose the status.json outside of the container for nginx. Can we improve this?
      - ./status:/opt/orbs/status
    env_file:
      - node.env



  
